---
# defaults file for upgrade

# this role requires `nextcloud_webroot` to be set, defaults to `/opt/nextcloud`.
# `nextcloud_websrv_user` needs to be set as well, defaults to `www-data`.

nextcloud_initial_version: '{{ nextcloud_upgrade_path | first }}'
nextcloud_target_version: '{{ nextcloud_upgrade_path | last }}'

nextcloud_upgrade_path:
- 20.0.14
- 21.0.9
- 22.2.10
- 23.0.12
- 24.0.12
- 25.0.13
- 26.0.13
- 27.1.11
- 28.0.14
- 29.0.16
- 30.0.17 # EOL
- 31.0.13 # https://nextcloud.com/changelog/#latest31
- 32.0.5  # https://nextcloud.com/changelog/#latest32

# References:
# - https://nextcloud.com/changelog/
# - https://docs.nextcloud.com/server/latest/admin_manual/maintenance/upgrade.html
# - https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html
