---
# Upgrade one step in the path, from `current_nextcloud_version` to `current_step_nextcloud_version`

# Check version we are upgrading to

# Check PHP version compatibility
- name: Run PHP version compatibility check
  ansible.builtin.include_tasks: php_version_check.yml

- name: Run version checks
  ansible.builtin.include_tasks: version_check.yml

# Tasks to run before the upgrade

- name: Specific tasks before upgrade to version {{ current_step_nextcloud_version }}
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - upgrade/tasks_pre_{{ current_step_nextcloud_version }}.yml
        - upgrade/tasks_pre_{{ step_version_members[0:2] | join('.') }}.yml
        - upgrade/tasks_pre_{{ step_version_members[0] | string }}.yml
      skip: true
  vars:
    step_version_members: "{{ current_step_nextcloud_version | ansible.builtin.split('.') }}"

# Upgrade step

- name: Run upgrade with maintenance mode
  become: true
  become_user: "{{ nextcloud_websrv_user | default('www-data') }}"
  module_defaults:
    ansible.builtin.command:
      chdir: "{{ nextcloud_webroot | default('/opt/nextcloud') }}"
  block:
    - name: Enable maintenance mode before upgrade
      ansible.builtin.command: php occ maintenance:mode --on
      changed_when: true

    - name: Upgrade Nextcloud to version {{ current_step_nextcloud_version }}
      ansible.builtin.command: "php {{ nextcloud_webroot | default('/opt/nextcloud') }}/updater/updater.phar  --no-interaction"
      changed_when: true

    - name: Disable maintenance mode after upgrade
      ansible.builtin.command: php occ maintenance:mode --off
      changed_when: true

- name: Set current version to upgraded
  ansible.builtin.set_fact:
    current_nextcloud_version: '{{ current_step_nextcloud_version }}'

# Tasks to run after the upgrade

- name: Add missing indices
  become: true
  become_user: "{{ nextcloud_websrv_user | default('www-data') }}"
  ansible.builtin.command: php occ -vvv db:add-missing-indices
  args:
    chdir: "{{ nextcloud_webroot | default('/opt/nextcloud') }}"
  changed_when: true

- name: Specific tasks after upgrade to version {{ current_step_nextcloud_version }}
  ansible.builtin.include_tasks: '{{ item }}'
  with_first_found:
    - files:
        - upgrade/tasks_post_{{ current_step_nextcloud_version }}.yml
        - upgrade/tasks_post_{{ step_version_members[0:2] | join('.') }}.yml
        - upgrade/tasks_post_{{ step_version_members[0] | string }}.yml
      skip: true
  vars:
    step_version_members: "{{ current_step_nextcloud_version | ansible.builtin.split('.') }}"

...
